In [1]:
# Numpy

# 기본적으로 수학을 하는 데 가장 많이 쓰는 module
# C언어로 개발된 Python에서 과학적계산을 위한 핵심 라이브러리. 다차원 배열 객체와 함께 작동하는 도구들을 제공한다.
# 하지만 고수준의 데이터분석 기능을 제공하지 않기 떄문에 Numpy 계열과 Pandas와 같은 도구를 함께 사용!

# 기본적으로 설치되어 있진 않음
# https://compmath.korea.ac.kr/appmath/NumpyBasics.html -> numpy 참고 블로그

In [5]:
# Numpy 설치

import numpy as np    # as np -> 이제 numpy를 np라는 별명으로 사용하겠다! 
# Aliasing : 객체가 한 개 이상의 이름을 갖게 됨 by Reference
# https://seungjuitmemo.tistory.com/14

In [13]:
# Numpy 배열 만들기

numbers = [1,2,3,4]          #  numbers 라는 list array 생성
arr = np.array(numbers)   # [1,2,3,4] List를 배열하겠다. / numpy.array method 사용
print(arr)
print(type(arr))                # type은 Numpy array라는 새로운 배열로 type이 나온다.

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
# (좌표)
# value 1은 1차원 : 값만 생김

# (선)
# value 2는 2차원 : 방향이 생김 -> 선의 형태 (vector)

# (정사각형)
# value 3는 3차원 : 입체가 생김 -> 우리가 인식할 수 있는 한계

# 그 이상의 차원은 우리가 상상해야함 -> 기본적인 구조를 Numpy가 설정해줌.

In [22]:
# Zeros, ones, empty를 사용해서 배열을 생성한다

car = np.zeros((3,3))   # 초기 데이터를 0으로 초기화! 그리고 3,3 배열이 생김 -> 3차원 배열
#   zeros는 기본적으롤 array를 다루기 때문에, 행열을 설정하고 싶다면 
#   ( 행수, 열수 ) 의 형태로 괄호를 써야함!
print(car)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
np.ones((2,2)) # 2차원 배열을 1로 초기화 한다!

array([[1., 1.],
       [1., 1.]])

In [41]:
randomN = np.random.randn(4,4)      #empty method를 설명하기 위해 랜덤 array를 생성!
print(randomN)
print('----초기화 이후----')
empty44 = np.empty((4,4)) # 아무런 초기값을 지정하지 않고, 초기화를 진행함! array는 4차원
print(empty44)

# 초기화를 해도 그대로 Data가 남아있다. 
# 프로그램의 데이터를 지우고 나면, 실제로 지워지지 않음 -> 컴퓨터 상에 '지웠음' 이라고 뜰 뿐...
# 그래서 초기화를 시켜야 가장 깔끔하게 데이터가 지워짐 하지만 0으로 초기화 시키려면 
# 부하가 생기게 된다. 그래서 0으로 초기화 하는게 아니라 empty를 사용하면 
# 이전의 찌꺼기가 들어가있음..!

[[ 0.62187997 -1.13611513  0.89216477 -1.36413347]
 [ 1.25265431 -2.00189445 -1.23494545 -0.84050141]
 [ 0.46702544  0.35813288  0.42566918 -0.7985296 ]
 [-1.40614452  1.30951424 -0.19067034  0.08998758]]
----초기화 이후----
[[0.62187997 1.13611513 0.89216477 1.36413347]
 [1.25265431 2.00189445 1.23494545 0.84050141]
 [0.46702544 0.35813288 0.42566918 0.7985296 ]
 [1.40614452 1.30951424 0.19067034 0.08998758]]


In [62]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인해보기

arr1D = np.array([1,2,3])                                                  # 1차원
arr2D = np.array([[1,2,3],[4,5,6]])                                     # 2차원
# [ ] : 1차원 / [ [ ] ]: /2차원 / [ [ [ ] ] ]: 3차원

#  numpy.array() method 안에 list array 형태로 들어가야하지만, 
#  2차원 이기 때문에 대괄호가 2개!
print(arr1D,'\n')
print(arr2D,'\n')

[1 2 3] 

[[1 2 3]
 [4 5 6]] 



In [70]:
# 데이터의 차원(dimension)을 확인

print(arr1D.ndim)
print(arr2D.ndim)   #dimension 차원을 확인!

1
2


In [72]:
# 데이터의 모양(shape)을 확인

arr2D.shape # 데이터의 배열 모양을 모여줌!

(2, 3)

In [79]:
# 데이터의 타입(type)을 확인

print(type(arr2D))  # arr2D의 type을 알려줘!
print(arr2D.dtype)
# dtype : data type -> array '안'의 data type을 확인 할 수 있다!
# int64(integer 64 = 64bit 정수)

# 8bit : -128 0 +127 까지 표시가 가능함 
# 16bit : -32768 0 +32767 까지 표시가 가능함 
# 64bit : 왠만하면 모든 숫자를 표기 가능..!
# 하지만 메모리 낭비나 처리속도 저하가 생길 수 있음. 
# 그래서 필요한 정도만 테이터 타입을 불러서 사용..
# uint : 음수 값이 없는 int값

<class 'numpy.ndarray'>
int32


In [84]:
# ndarray 배열의 타입 변환

arr_int = np.array([1,2,3,4])
print(arr_int.dtype)
arr_float = arr_int.astype(np.float64)      # astype( ) method : 괄호 안의 type으로 바꾸고 싶다.
#   np.int32 -> np.float64 type 변환
print(arr_float.dtype)

int32
float64


In [89]:
# 배열의 연산기능 : 사칙연산
# 배열을 사용하는 이유!

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
# 2D array를 2개 생성

print(arr1 + arr2,'\n')  # 같은 차원의 애들끼리 연산을 해줌. 1,2 + 5,6 / 3,4 + 7,8
print(arr1 - arr2,'\n')  # 뺄셈
print(arr1 * arr2)  # 곱셈

[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]]


In [90]:
# 배열의 연산기능 : Method

print(np.add(arr1, arr2),'\n')       # method를 이용한 방법도 있다! add(+)
print(np.multiply(arr1, arr2))  # multiply : 곱셈

# 여러개의 메소드를 사용할 때는 print를 꼭 붙여서 사용하기
# numpy에서는 instance를 사용하지 않아도 크게 문제가 없음


[[ 6  8]
 [10 12]] 

[[ 5 12]
 [21 32]]


In [118]:
# nparray Slicing 해보기

arr_1 = arr[:1, :3]
# :1 -> 앞 에서 부터 1번 list까지 -> [1,2,3]중에서
# 0:3 -> index 0에서 2까지 -> [1,2]추출 
# 실제로 index 3의 데이터는 존재 하지 않지만, 문법상 int type의 slicing은 a:b-1 까지 취급

arr_2 = arr[ :2, 1:3 ]
# :2 -> 앞 에서 부터 2번 list까지 -> [1,2,3], [4,5,6] 중에서
# 1:3 -> index 1에서 2까지 -> [2,3], [5,6] 추출 

print(arr,'\n')
print(arr_1,'\n')
print(arr_2,'\n')

[[1 2 3]
 [4 5 6]] 

[[1 2 3]] 

[[2 3]
 [5 6]] 



In [122]:
# nparray 원하는 값 추출하기

arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr[0,2] # 0번 list의 2번 index -> 3

3

In [126]:
# nparray 조건식 부여하기

arr = np.array([[1,2,3],
               [4,5,6]])
idx = arr > 3   # arr의 index의 값이 3보다 큰가요? 
print(idx)

[[False False False]
 [ True  True  True]]


In [130]:
# true or false의 결과를 받고

arr[idx]
# 그 데이터를 가지고, 값을 추출!

array([4, 5, 6])

In [150]:
# csv 파일 불러오기
# https://firework-ham.tistory.com/49 -> numpy csv 파일 불러오기

redwine = np.loadtxt(fname='../99_Src/csv/winequality-red.csv', delimiter=';', skiprows=1)
# fname : file name -> 불러올 파일의 이름 (나의 경우는 ./99_Src/csv 폴더에 있음)
# delimiter : 불러온 csv 파일의 구분자에 따라서 맞춰줘야함! ->  ; 로 구분
# skiprows = 1 -> 첫 번째 줄은 건너뜀

In [156]:
print(redwine)  # 정상적으로 csv 파일이 불러짐!
print(redwine.dtype)    # 소수점도 있기 때문에 실수 float type!
redwine.shape     # scv의 모양  row 1599개 / column 12개

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]
float64


(1599, 12)

In [141]:
# 기초 통계 함수 정리

# sum : 합계
# mean : 평균
# std : 표준 편차
# var : 분산 (std의 제곱) -> 표준편차를 확대해서 더 극적이게 보임
# min : 최소값
# max : 최대값


In [153]:
print(redwine.sum(),'\n')  
# 전체 데이터의 합계 
# -> 이 자체는 의미가 크게 없음, column별로 데이터를 만드는 것이 중요!

print(redwine.sum(axis=0),'\n') 
# 자신이 원하는 방향(축)을 중심으로 결과를 내야함

print(redwine.mean(axis=0),'\n') 
# 평균을 찾기 / 5점대가 평균, 퀄리티, 5 이상이면 평균이상! 
# 알콜은 10도 이상이 되어야 평균

# 가로 : 0번축 = 칼럼별 평균 / 세로 : 1번축 = 항목별 평균
# http://taewan.kim/post/numpy_sum_axis/#case-1-axis-none -> numpy array의 이해
# axis(축) : array의 dimension에 따라서 주어지며, n차원은 n-1의 axis를 가짐.
# axis는 데이터를 방향(x축, y축, depth축)에 따라 합을 해준다.

152084.78194 

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ] 

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251] 



In [160]:
print(redwine[:,0].mean()) # 전체 row(value)중 0번 column(key)의 평균을 구한다.
# 실제 scv의 0번 column(key)는 fixed acidity다. 그 평균값!

8.31963727329581


In [163]:
print(redwine.max(axis=0))  # 각 column 최대  value들
print(redwine.min(axis=0))  # 각 column의 최소  value들

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]
[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]
